server:
  port: 5000
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.db.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
  kafka:
    bootstrap-servers: ${rds.hostname}:${rds.kafka.port}
    consumer:
      group-id: sns
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    listener:
      ack-mode: MANUAL
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: alarm
jwt:
  secret-key: 2023-postype.sns-application-project.secret_key
  token.expired-time-ms: 2592000000
