spring.jpa:
    database: mysql
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
    show-sql: true

spring.datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:mysql://localhost:3306/sns_contents?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: posType.sns-application-2023.secret_key
  # 30days
  token.expired-time-ms: 2592000000
